application: md-docs
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /(.*\.(gif|png|jpg|ico|js|css|json|html|svg))
  static_files: static/\1
  upload: static/(.*\.(gif|png|jpg|ico|js|css|json|html|svg))

- url: .*
  script: main.app

- url: /(.*?)/(.*)
  script: main.\1.\2.app

libraries:
- name: webapp2
  version: "2.5.2"
